### PR TITLE
Converting install script + upgraded deprecated code

### PR DESCRIPTION
**Pull request by Arteneko**

### CODE REVIEW

**Comment by Arteneko** [comment]
I couldn't understand some parts of the script, e.g. the `runApp`, and some tasks require renaming to be able to work with other tasks.

**Comment by ashokgelal** [comment]
Nice! I like where you are going with this! Thank you already for taking this initiative. If you want to talk more about it or need any clarification around the script, please feel free to [send me a DM in our official Slack](https://join.slack.com/t/alpasdev/shared_invite/enQtODcwMjE1MzMxODQ3LTJjZWMzOWE5MzBlYzIzMWQ2MTcxN2M2YjU3MTQ5ZDE4NjBmYjY1YTljOGIwYmJmYWFlYjc4YTcwMDFmZDIzNDE)

**Comment by Arteneko** [comment]
Since I'm not particularly comfortable with using Slack (and since it constantly crashes on my computer), would dev.to tchat pass?

**Comment by ashokgelal** [comment]
Definitely!

**Comment by ashokgelal** [comment]
I guess we both need to follow each other to be able to send direct messages on dev.to

**Pull request closed without merging**
